### ISSUE TITLE
install error on wsgiref 0.1.2

### ISSUE THREAD

**Issue by jeremytarling** [yefim/flask-heroku-sample#6]
hi there, my install fails at this step:

$ pip install -r requirements.txt
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
Collecting Flask-SQLAlchemy==2.1 (from -r requirements.txt (line 2))
  Using cached Flask-SQLAlchemy-2.1.tar.gz
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Using cached MarkupSafe-0.23.tar.gz
Collecting SQLAlchemy==1.1.3 (from -r requirements.txt (line 5))
  Downloading SQLAlchemy-1.1.3.tar.gz (5.1MB)
Collecting Werkzeug==0.11.11 (from -r requirements.txt (line 6))
  Downloading Werkzeug-0.11.11-py2.py3-none-any.whl (306kB)
Collecting click==6.6 (from -r requirements.txt (line 7))
  Downloading click-6.6-py2.py3-none-any.whl (71kB)
Collecting gunicorn==19.6.0 (from -r requirements.txt (line 8))
  Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
Collecting itsdangerous==0.24 (from -r requirements.txt (line 9))
  Using cached itsdangerous-0.24.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
  Downloading wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tarlij01\AppData\Local\Temp\pip-build-0j656hmv\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\tarlij01\AppData\Local\Temp\pip-build-0j656hmv\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\tarlij01\AppData\Local\Temp\pip-build-0j656hmv\wsgiref\
(venv)

so that looks like a python vs python3 print brackets error in wsgiref 0.1.2 I think? 

Looking at the docs https://pypi.python.org/pypi/wsgiref says 
"This is a standalone release of the wsgiref library, that provides validation support for WSGI 1.0.1 (PEP 3333) for Python versions < 3.2, and includes the new wsgiref.util.test() utility function."

$ python -V
Python 3.6.0
(venv)

So I'm wondering whether to downgrade to an older Python that works with wsgiref or use a different WSGI?

cheers

JT

**Comment by yefim** [comment]
Hey @jeremytarling, I think if you update wsgiref to the newest version, it should work. See https://docs.python.org/3/library/wsgiref.html

**Comment by yefim** [comment]
@jeremytarling I updated this boilerplate to use Pipenv so hopefully it works now!
