### ISSUE TITLE
db.create_all() doesn't run on the first deploy

### ISSUE THREAD

**Issue by Hiyorimi** [yefim/flask-heroku-sample#9]
Hey! thanks for the great starter's repo.

I'm new to heroku, so I haven't figured out how to run db.create_all() after setup, luckily, for single page demo, I don't need a db. I'm just curious: so how is it supposed to be done?

And not to create another issue: have you considered migrating to python 3 ?

**Comment by yefim** [comment]
To run `db.create_all()` on Heroku you would need to open a Python shell on the Heroku server. You can achieve it by running: `heroku run python`. From there you should have access to your app so you could run `from app import db` and then `db.create_all()`. Hope that helps :)

As far as migrating to Python 3, I think it would be easy so if you're feeling gracious, I would appreciate if you could take a stab at it and I'll review your PR. Best of luck!

**Comment by Hiyorimi** [comment]
Thanks!

**Comment by Hiyorimi** [comment]
[Here](https://github.com/yefim/flask-heroku-sample/pull/10) you are.

**Comment by yefim** [comment]
Ooh thanks :) Will take a look this weekend!
